name: Deploy to Launch 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check for .cs-launch file
        run: |
         echo "Current directory:"
         pwd
         echo "Files including dotfiles:"
         ls -la

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Show latest commit ID and message
        run: |
            echo "Latest Commit ID:"
            git log -1 --pretty=format:"%H"
            echo ""
            echo "Latest Commit Message:"
            git log -1 --pretty=format:"%s"

      - name: Install CLI tools
        run:
          npm install -g @contentstack/cli
      
      - name: Install otplib
        run: npm install otplib

      - name: Verify Contentstack CLI Installation
        run: csdx --version

      - name: Set Launch Region
        run: csdx config:set:region AWS-NA

      - name: Login to Contentstack via CSDX CLI
        env:
          CSDX_EMAIL: ${{ secrets.CSDX_EMAIL }}
          CSDX_PASSWORD: ${{ secrets.CSDX_PASSWORD }}
          CSDX_TOTP_SECRET: ${{ secrets.CSDX_TOTP_SECRET }}
        run: node csdx-login.js

      - name: Verify CSDX Login
        run: csdx auth:whoami

      - name: Deploy using Launch config
        run: 
          csdx launch --redeploy-latest 
          
        # ADD ENVIRONMENT FLAG IF YOU HAVE DIFFERENT ENVIRONMENT AND YOU WANT TO DEPLOY IN THE SPECIFIC ENVIRONMENT
        # --environment EnvironmentName 

        # ADD CONFIG FLAG IF YOU .cs-launch.json IS NOT IN THE ROOT DIRECTORY
        # --config Path_to_launch_config_file
